import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from 'next/font/google'
// import { Inconsolata } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import LayoutWrapper from "./LayoutWrapper";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const poppins = Poppins({
  weight: ['400','500','600','700','800', '900'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

// const inconsolata = Inconsolata({
//   weight: ['400','500','600','700','800', '900'],
//   style: ['normal'],
//   subsets: ['latin'],
//   display: 'swap',
// }) 

export const metadata: Metadata = {
  title: "Book-SHOP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.className}`}>
      <head>
        <link rel="stylesheet" href="/icons/css/all.min.css" />
      </head>
      <body className="flex flex-col min-h-screen">
        <LayoutWrapper>
          <Header />
          <main className="flex-grow container mx-auto bg-white">
            {children}
          </main>
          <Footer />
        </LayoutWrapper>
      </body>
    </html>
  );
}
