export const books = [
  {
    _id: "1",
    images: ["/images/mock-books/alchemist.jpg"],
    title: "The Alchemist",
    category: "Reading Books (Novels)",
    condition: "Excellent",
    classType: "B.Com",
    subject: "Fiction",
    genre: "Fiction",
    year: "1988",
    price: 350,
    author: "Paulo Coelho",
    edition: "1st Edition",
    description: "A global phenomenon, The Alchemist has been read and loved by over sixty-two million readers.",
    finalPrice: 300,
    shippingCharge: 50,
    paymentMode: "SSLCommerz",
    paymentDetails: {
      sessionId: "ssl_123456789",
    },
    createdAt: new Date("2024-01-01"),
    seller: { name: "John Doe", contact: "1234567890" },
  },
  {
    _id: "2",
    images: ["/images/mock-books/becoming.jpg"],
    title: "Becoming",
    category: "Reading Books (Biography)",
    condition: "Excellent",
    classType: "MBA",
    subject: "Biography",
    genre: "Biography",
    year: "2018",
    price: 650,
    author: "Michelle Obama",
    edition: "1st Edition",
    description: "In her memoir, a work of deep reflection and mesmerizing storytelling, Michelle Obama invites readers into her world.",
    finalPrice: 600,
    shippingCharge: 50,
    paymentMode: "Bank Account",
    paymentDetails: {
      bankDetails: {
        accountNumber: "1234567890123456",
        bicCode: "DBBLBDDH001",
        bankName: "Dutch-Bangla Bank",
      },
    },
    createdAt: new Date("2024-01-02"),
    seller: { name: "Jane Smith", contact: "0987654321" },
  },
  {
    _id: "3",
    images: ["/images/mock-books/data-structures-and-algorithms-made-easy.jpg"],
    title: "Data Structures and Algorithms Made Easy",
    category: "Technical Books",
    condition: "Excellent",
    classType: "B.Tech",
    subject: "Computer Science",
    genre: "Programming",
    year: "2011",
    price: 550,
    author: "Narasimha Karumanchi",
    edition: "5th Edition",
    description: "A handy guide of data structures and algorithms for every computer scientist.",
    finalPrice: 500,
    shippingCharge: 40,
    paymentMode: "SSLCommerz",
    paymentDetails: {
      sessionId: "ssl_987654321",
    },
    createdAt: new Date("2024-01-03"),
    seller: { name: "Rahul Gupta", contact: "1122334455" },
  },
  {
    _id: "4",
    images: ["/images/mock-books/ignited-minds.jpg"],
    title: "Ignited Minds",
    category: "Inspirational",
    condition: "Excellent",
    classType: "General",
    subject: "Self-Help",
    genre: "Motivational",
    year: "2002",
    price: 300,
    author: "A.P.J. Abdul Kalam",
    edition: "1st Edition",
    description: "Unleashing the Power Within India by A.P.J. Abdul Kalam.",
    finalPrice: 250,
    shippingCharge: 30,
    paymentMode: "Bank Account",
    paymentDetails: {
      bankDetails: {
        accountNumber: "6543210987654321",
        bicCode: "BRACBDDH002",
        bankName: "BRAC Bank",
      },
    },
    createdAt: new Date("2024-01-04"),
    seller: { name: "Alice Brown", contact: "2233445566" },
  },
  {
    _id: "5",
    images: ["/images/mock-books/introduction-to-algorithms.jpg"],
    title: "Introduction to Algorithms",
    category: "Technical Books",
    condition: "Excellent",
    classType: "B.Sc",
    subject: "Algorithms",
    genre: "Programming",
    year: "2009",
    price: 1200,
    author: "Thomas H. Cormen",
    edition: "3rd Edition",
    description: "A comprehensive guide to the modern study of computer algorithms.",
    finalPrice: 1100,
    shippingCharge: 60,
    paymentMode: "SSLCommerz",
    paymentDetails: { sessionId: "ssl_456789012" },
    createdAt: new Date("2024-01-05"),
    seller: { name: "Michael Johnson", contact: "3344556677" },
  },
  {
    _id: "6",
    images: ["/images/mock-books/sapiens.jpg"],
    title: "Sapiens: A Brief History of Humankind",
    category: "Reading Books (History)",
    condition: "Excellent",
    classType: "General",
    subject: "History",
    genre: "History",
    year: "2011",
    price: 600,
    author: "Yuval Noah Harari",
    edition: "1st Edition",
    description: "A book that spans the whole of human history, from the very first humans to walk the earth to the radical—and sometimes devastating—breakthroughs of the Cognitive, Agricultural, and Scientific Revolutions.",
    finalPrice: 550,
    shippingCharge: 40,
    paymentMode: "Bank Account",
    paymentDetails: {
      bankDetails: {
        accountNumber: "7890123456789012",
        bicCode: "IBBLBDDH003",
        bankName: "Islami Bank Bangladesh",
      },
    },
    createdAt: new Date("2024-01-06"),
    seller: { name: "Emily Davis", contact: "4455667788" },
  },
  {
    _id: "7",
    images: ["/images/mock-books/the-catcher-in-the-eye.webp"],
    title: "The Catcher in the Rye",
    category: "Reading Books (Novels)",
    condition: "Excellent",
    classType: "General",
    subject: "Literature",
    genre: "Fiction",
    year: "1951",
    price: 400,
    author: "J.D. Salinger",
    edition: "1st Edition",
    description: "A classic novel about teenage angst and alienation.",
    finalPrice: 350,
    shippingCharge: 30,
    paymentMode: "SSLCommerz",
    paymentDetails: { sessionId: "ssl_112233445" },
    createdAt: new Date("2024-01-07"),
    seller: { name: "Sarah Wilson", contact: "5566778899" },
  },
  {
    _id: "8",
    images: ["/images/mock-books/the-great-gatsby.jpg"],
    title: "The Great Gatsby",
    category: "Reading Books (Novels)",
    condition: "Excellent",
    classType: "General",
    subject: "Literature",
    genre: "Fiction",
    year: "1925",
    price: 350,
    author: "F. Scott Fitzgerald",
    edition: "1st Edition",
    description: "A story of ambition, love, and the American Dream in the 1920s.",
    finalPrice: 300,
    shippingCharge: 20,
    paymentMode: "Bank Account",
    paymentDetails: {
      bankDetails: {
        accountNumber: "1234567890123456",
        bicCode: "IFICBDDH004",
        bankName: "IFIC Bank",
      },
    },
    createdAt: new Date("2024-01-08"),
    seller: { name: "David Lee", contact: "6677889900" },
  },
  {
    _id: "9",
    images: ["/images/mock-books/the_7_habits.jpg"],
    title: "The 7 Habits of Highly Effective People",
    category: "Inspirational",
    condition: "Excellent",
    classType: "General",
    subject: "Self-Help",
    genre: "Motivational",
    year: "1989",
    price: 450,
    author: "Stephen Covey",
    edition: "1st Edition",
    description: "A business and self-help book that has sold more than 25 million copies worldwide.",
    finalPrice: 400,
    shippingCharge: 25,
    paymentMode: "SSLCommerz",
    paymentDetails: { sessionId: "ssl_556677889" },
    createdAt: new Date("2024-01-09"),
    seller: { name: "Laura Green", contact: "7788990011" },
  },
  {
    _id: "10",
    images: ["/images/mock-books/thinking-fast-and-slow.jpg"],
    title: "Thinking, Fast and Slow",
    category: "Reading Books (Non-Fiction)",
    condition: "Excellent",
    classType: "General",
    subject: "Psychology",
    genre: "Non-Fiction",
    year: "2011",
    price: 700,
    author: "Daniel Kahneman",
    edition: "1st Edition",
    description: "A book that explains the two systems that drive the way we think.",
    finalPrice: 650,
    shippingCharge: 40,
    paymentMode: "Bank Account",
    paymentDetails: {
      bankDetails: {
        accountNumber: "2345678901234567",
        bicCode: "PUBABDDH005",
        bankName: "Pubali Bank",
      },
    },
    createdAt: new Date("2024-01-10"),
    seller: { name: "Chris Brown", contact: "8899001122" },
  },
  {
    _id: "11",
    images: [],
    title: "Himu",
    category: "Reading Books (Novels)",
    condition: "Excellent",
    classType: "B.Sc",
    subject: "Fiction",
    genre: "Fiction",
    year: "2023",
    price: 400,
    author: "Humayun Ahmed",
    edition: "1st Edition",
    description: "A popular novel from the Himu series by Humayun Ahmed.",
    finalPrice: 350,
    shippingCharge: 30,
    paymentMode: "SSLCommerz",
    paymentDetails: { sessionId: "ssl_334455667" },
    createdAt: new Date("2024-01-11"),
    seller: { name: "Ahmed Khan", contact: "3344556677" },
  },
  {
    _id: "12",
    images: [],
    title: "Misir Ali",
    category: "Reading Books (Novels)",
    condition: "Good",
    classType: "MBA",
    subject: "Fiction",
    genre: "Fiction",
    year: "2023",
    price: 450,
    author: "Humayun Ahmed",
    edition: "1st Edition",
    description: "A mystery novel from the Misir Ali series.",
    finalPrice: 400,
    shippingCharge: 25,
    paymentMode: "Bank Account",
    paymentDetails: {
      bankDetails: {
        accountNumber: "3456789012345678",
        bicCode: "SONALIBDDH006",
        bankName: "Sonali Bank",
      },
    },
    createdAt: new Date("2024-01-12"),
    seller: { name: "Fatima Begum", contact: "4455667788" },
  },
  {
    _id: "13",
    images: [],
    title: "Charulata",
    category: "Reading Books (Novels)",
    condition: "Fair",
    classType: "B.Com",
    subject: "Fiction",
    genre: "Fiction",
    year: "2023",
    price: 350,
    author: "Rabindranath Tagore",
    edition: "1st Edition",
    description: "A novel by Rabindranath Tagore about a neglected wife.",
    finalPrice: 300,
    shippingCharge: 20,
    paymentMode: "SSLCommerz",
    paymentDetails: { sessionId: "ssl_778899001" },
    createdAt: new Date("2024-01-13"),
    seller: { name: "Rina Ahmed", contact: "5566778899" },
  },
  {
    _id: "14",
    images: [],
    title: "The Golden Age",
    category: "Reading Books (Novels)",
    condition: "Excellent",
    classType: "12th",
    subject: "Fiction",
    genre: "Fiction",
    year: "2023",
    price: 500,
    author: "Tahmima Anam",
    edition: "1st Edition",
    description: "A novel about a family in Bangladesh during the war.",
    finalPrice: 450,
    shippingCharge: 30,
    paymentMode: "Bank Account",
    paymentDetails: {
      bankDetails: {
        accountNumber: "4567890123456789",
        bicCode: "JANATABDDH007",
        bankName: "Janata Bank",
      },
    },
    createdAt: new Date("2024-01-14"),
    seller: { name: "Sadia Islam", contact: "6677889900" },
  },
  {
    _id: "15",
    images: [],
    title: "Padma Nadir Majhi",
    category: "Reading Books (Novels)",
    condition: "Good",
    classType: "B.Tech",
    subject: "Fiction",
    genre: "Fiction",
    year: "2023",
    price: 400,
    author: "Manik Bandopadhyay",
    edition: "1st Edition",
    description: "A classic Bengali novel about boatmen on the Padma River.",
    finalPrice: 350,
    shippingCharge: 25,
    paymentMode: "SSLCommerz",
    paymentDetails: { sessionId: "ssl_112233445" },
    createdAt: new Date("2024-01-15"),
    seller: { name: "Tania Rahman", contact: "7788990011" },
  },
  {
    _id: "16",
    images: [],
    title: "The Tale of the Four Durwans",
    category: "Reading Books (Short Stories)",
    condition: "Fair",
    classType: "11th",
    subject: "Literature",
    genre: "Classic",
    year: "1950",
    price: 300,
    author: "Rabindranath Tagore",
    edition: "1st Edition",
    description: "A collection of short stories by Rabindranath Tagore.",
    finalPrice: 250,
    shippingCharge: 20,
    paymentMode: "Bank Account",
    paymentDetails: {
      bankDetails: {
        accountNumber: "5678901234567890",
        bicCode: "AGRICULTBDDH008",
        bankName: "Agrani Bank",
      },
    },
    createdAt: new Date("2024-01-16"),
    seller: { name: "Nadia Hossain", contact: "8899001122" },
  },
  {
    _id: "17",
    images: [],
    title: "The Hungry Tide",
    category: "Reading Books (Novels)",
    condition: "Excellent",
    classType: "M.Sc",
    subject: "Fiction",
    genre: "Fiction",
    year: "2023",
    price: 600,
    author: "Amitav Ghosh",
    edition: "1st Edition",
    description: "A novel set in the Sundarbans of Bangladesh and India.",
    finalPrice: 550,
    shippingCharge: 35,
    paymentMode: "SSLCommerz",
    paymentDetails: { sessionId: "ssl_223344556" },
    createdAt: new Date("2024-01-17"),
    seller: { name: "Farhana Karim", contact: "9900112233" },
  },
  {
    _id: "18",
    images: [],
    title: "The Village by the Sea",
    category: "Reading Books (Novels)",
    condition: "Good",
    classType: "10th",
    subject: "Fiction",
    genre: "Fiction",
    year: "2023",
    price: 350,
    author: "Anita Desai",
    edition: "1st Edition",
    description: "A novel about a family in a coastal village.",
    finalPrice: 300,
    shippingCharge: 25,
    paymentMode: "Bank Account",
    paymentDetails: {
      bankDetails: {
        accountNumber: "6789012345678901",
        bicCode: "RUPALIBDDH009",
        bankName: "Rupali Bank",
      },
    },
    createdAt: new Date("2024-01-18"),
    seller: { name: "Shamim Akter", contact: "0011223344" },
  },
];

export const filters = {
  condition: ["Excellent", "Good", "Fair"],
  category: [
    "College Books (Higher Education Textbooks)",
    "Exam/Test Preparation Books",
    "Reading Books (Novels, Children, Business, Literature, History, etc.)",
    "School Books (up to 12th)",
  ],
  classType: [
    "B.Tech",
    "B.Sc",
    "B.Com",
    "BCA",
    "MBA",
    "M.Tech",
    "M.Sc",
    "Ph.D",
    "12th",
    "11th",
    "10th",
    "9th",
    "8th",
    "7th",
    "6th",
    "5th",
  ],
  genre: [
    "Fiction",
    "Non-Fiction",
    "Detective",
    "Mystery & Thriller",
    "Romance",
    "Sci-Fi",
    "Fantasy",
    "Biography",
    "History",
    "Business",
    "Crime",
    "Action",
    "Horror",
    "Poetry",
    "Comics",
    "Art",
    "Food & Drinks",
    "Journals",
    "Religion",
    "Travel",
    "Classic",
    "Motivational",
    "Humanities & Social Sciences",
  ],
  author: [
    "Tahmima Anam",
    "Neamat Imam",
    "Taslima Nasrin",
    "Monica Ali",
    "Kaji Nazrul Islam",
    "Humayun Ahmed",
    "Bibhutibhushan Bandyopadhyay",
    "Manik Bandopadhyay",
    "Amitav Ghosh",
    "Anita Desai",
  ],
  year: [
    "2023",
    "2022",
    "2021",
    "2020",
    "2019",
    "2018",
    "2012",
    "1950",
    "1910",
  ],
};
